export const EventData=[
    {
    id:"1",
   EventName:"Code Crunch",
   Participants:"Solo",
   EventDescription_p1:"Embark on a coding adventure that transcends skill levels! Whether you're a seasoned developer or just starting out, this event welcomes participants of all levels and backgrounds to tackle challenging coding problems. Test your skills, learn new techniques, and connect with fellow coding enthusiasts in a dynamic and engaging atmosphere.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound:null,

   Round1Title:"Round 1",
   Round1:" The first round will consist of 2 problems, assessing participant’s understanding of basic coding concepts and implementation.The top 30%ile of the participants will advance to the next round.",

   Round2Title:"Round 2",
   Round2:"Participants will be given a question of considerable difficulty which they will have to attempt and solve within the given time span. Participants need to solve as many test cases as possible. The ones to solve the maximum number of test cases in the shortest span of time will be judged as the winners.",

   Extraline1:"Estimated time: 3 hours ",
   Extraline2:"Only candidates who meet the criteria will advance to Round 2.",
   Extraline3:"In the second round, participants will be tested offline to assess their ability to understand problem statements. Duration: 1 hour",
   Rule1:"1. Eligibility: The event is open to individuals with coding proficiency, irrespective of experience level.",
   Rule2:"2.Test Cases: Code submissions will be evaluated based on their ability to pass predefined test cases. The number of test cases passed will contribute to the overall score.",
   Rule3:"3.Language: Participants can use any coding language of their choice to solve the problem",
   Rule4:"4.Judging Decisions: All judging decisions are final and binding. No appeals or disputes will be entertained. The event Coordinator reserves the right to disqualify any participant at any time during the event.",
   Rule5:"5.Platform Usage: Participants must exclusively use HackerRank platform for all coding tasks. Switching tabs or copy-pasting from external sources during the contest is strictly prohibited and will be considered malpractice.",
   Rule6:"6.Code Submission: All code submissions must be made within the specified time frame on HackerRank platform. Late submissions will not be accepted.",

   EventHead1:"MANO DHASHIN D",
   Contact1:"9025067200",
   EventHead2:" GAYATHRI D",
   Contact2:" 9884974740",
   link:"https://forms.gle/BMf6G9auSNX2HVqJ6",
   Timing:"12:00-3:00 PM",
Venue: "DG001 (D Block) - Rajalakshmi Engineering College"
},{
    id:"2",
    EventName:"Beyond Buttons (UI/UX)",
    Participants:"Solo/Team[Max:3]",
    EventDescription_p1:"A UI/UX-based event presents participants with a problem statement that requires creative and unique solutions. The objective of the UI/UX event is to inspire individuals to develop digital experiences that prioritize end-users. ",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
//    PreliminaryRoundTItle:"Preliminary Round",
//    PreliminaryRound:"During this stage, participants will be tasked with creating a UI for an app or website using Figma online. They will need to refer to a given problem statement for guidance. Candidates will be evaluated solely on their Figma submissions, as images will not be considered as design work.",
   Round1Title:"UX Round",
   Round1:"In the first round, participants will be presented with a concept or a problem statement. The participants must ideate and come up with a feasible solution. The task is to quickly document and translate the problem statement into a wireframe—a skeletal outline that represents the structure and layout of a digital interface. Participants will have a limited amount of time to create a clear and intuitive wireframe that effectively communicates the functionality and flow of the proposed solution.",
   Round2Title:"UI Design Build",
   Round2:"In the second round, participants will take their wireframes to the next level by transforming them into visually stunning UI designs. Using their wireframes as a guide, participants will focus on incorporating color schemes, typography, imagery, and interactive elements to create a polished and user-friendly interface. Attention to detail, creativity, and adherence to design principles will be crucial in this round",
   Extraline1:"Presentation round:​In this final round, participants shortlisted from round 1 and 2 will have to present their design work to judges as final evaluation.",
   Extraline3:null,
   Rule1:"1.Open to all participants either individuals or a team of 2-3 peers.",
   Rule2:"2.Internet access is strictly prohibited in the UX Round, but it can be accessed in the UI Round.",
   Rule3:"3.Participants have to present their design work for evaluation.",
   Rule4:"4.All judging decisions are final and binding. No appeals or disputes will be entertained. The event lead reserves the right to disqualify any participant at any time during the event.",
   EventHead1:"Lingesh",
   Contact1:"9790895966",
   EventHead2:"AJAY KRISHNA",
   Contact2:"7305905373",
   link:"https://forms.gle/1qTu6FjMB2VWmRSG7",
   Timing: "8:30 - 12:00 PM",
    Venue: "DG001 (D Block) - Rajalakshmi Engineering College"

   

},{
    id:"7",
    EventName:"Best Out of waste",
    Participants:"Solo/Team[Max:3]",
    EventDescription_p1:"Best Out of Waste is an event where participants have the opportunity to showcase their creativity by repurposing old or unused items into innovative and practical creations. Sustainability is the primary focus so plastic items are strictly prohibited.",
   EventDescription_p2:"Material Selection: Participants have the freedom to choose from a variety of old or unused items, such as glass bottles, clothes, stationery and more.",
   EventDescription_p3:"Emphasizing creativity: Participants are urged to explore innovative approaches and generate distinctive concepts for the transformation of these items. Creativity is essential, whether it's expressed through painting, cutting, sewing, or any other method.",
   EventDescription_p4:"Functionality: In addition to being creative, participants should also take into account the practicality of their creations.",
   EventDescription_p5:"Presentation: Participants will have the chance to showcase their creations to the judges and other attendees. They should be able to discuss their creative process and the inspiration behind their work.",
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either individual or team 2-3.",
   Rule2:"2.The items required for the event, including old or unused items for transformation, should be procured by the participants themselves.",
   Rule3:"3. Organizers will not provide any additional materials or equipment during the event.",
   Rule4:"4.It is the participant's responsibility to double-check their supplies before the event to avoid any inconvenience or disruptions during the event.",
   Rule5:"5.All judging decisions are final and binding. No appeals or disputes will be entertained. The event Coordinators reserve the right to disqualify any participant at any time during the event.",
   Rule6:"6.Participants are requested to avoid plastic items.",
   EventHead1:"NAREN MB",
   Contact1:"9025770851",
   EventHead2:"RAMKUMAR",
   Contact2:"9488137463",
   link:"https://forms.gle/6ve9vZFZStZ5r9mp9",
   Timing: "8:30-11:30 AM",
Venue:"KS02 (Idea Factory) - Rajalakshmi Engineering College"

   
},{
    id:"6",
    EventName:"Movie Minds",
    Participants:"Team [2-4]",
    EventDescription_p1:"A movie quiz challenge in which participants demonstrate their expertise in the realm of cinema. It's an exciting adventure that challenges your memory, sharp eye for detail, and passion for film. The goal is to engage and push the participants by assessing their interpretation of movies. [You can understand the game as a version of the TV Show ‘Connections’]",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either as a Team of 2-4.",
   Rule2:"2. Participants should refrain from using mouth motions",
   Rule3:"3. Participants shouldn't ask for assistance from others.",
   Rule4:"4. Malpractice of any kind will result in immediate disqualification.",
   Rule5:"5. All judging decisions are final and binding. No appeals or disputes will be entertained. The event Coordinators reserve the right to disqualify any participant at any time during the event.",
   Rule6:null,
   EventHead1:"Madhumita M",
   Contact1:"9080224846",
   EventHead2:"Krishna Prasad C A",
   Contact2:"7358387750",
   link:"https://forms.gle/qxpYV2s5QTxvGPGV8",
   Timing: "12:30-3:00 PM",
    Venue: "KS01 (Idea Factory) - Rajalakshmi Engineering College"

},
{  
    id:"3",
    EventName:"TRADEMARK",
    Participants:"Solo",
    EventDescription_p1:"Join our exciting Logo Design Competition! And demonstrate your design skills by creating a one-of-a-kind logo that perfectly captures the essence of the given theme. We are looking for unique and visually captivating logos that perfectly represent our chosen theme. This competition offers participants the opportunity to showcase their exceptional design skills and potentially influence the brand identity of a significant organization or cause.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:"Design Round",
   Round1:"Participants need to choose one of the three topics given to them, ideate, and create a logo for the same.The logo must be creative, innovative and must not compromise on the theme of the topic chosen.Best 5 designs will be chosen for progressing to the next round.",
   Round2Title:"Final Round",    
   Round2:"In this round the finalists need to explain the main idea behind their choice of logo, what they believe the audience will interpret from their logo and how it showcases the main ideology of the selected theme.",
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Usage of mobile phones during the competition is strictly prohibited",
   Rule2:"2. Participants are allowed to use Google only during the ideation phase (15 mins)",
   Rule3:"3. Participants are allowed to use only Adobe Photoshop, Illustrator, Picsart and Figma to design logos.",
   Rule4:"4. All judging decisions are final and binding. No appeals or disputes will be entertained. The event coordinators reserve the right to disqualify any participant at any time during the event.",
   Rule5:null,
   Rule6:null,
   EventHead1:"Bharathi K",
   Contact1:"9940647260",
   EventHead2:"ADITHYA V",
   Contact2:"9444688165",
   link:"https://forms.gle/VVj1qGLtuX96fQqt7",
   Timing: "8:30-12:00 PM",
   Venue: "JL1 (Library Block) - Rajalakshmi Engineering College"
   

},
{   id:"8",
    EventName:"STORY ARCS",
    Participants:"Solo",
    EventDescription_p1:"Story Arcs is a comic competition where participants have the opportunity to showcase their creativity by adapting open-ended stories into comics, developing wordless narratives, and sketching stories. This event provides a platform for artists to express their creativity and captivate audiences through immersive visual storytelling. Artists demonstrate their storytelling abilities through illustrations.",
   EventDescription_p2:"Participants are given Comic frames (A3 sheet) and themes to work on!",
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Participants will receive A3 sheets with comic grids.",
   Rule2:"2.Every participant must bring their own art supplies.",
   Rule3:"3.Theme Selection: Participants will be presented with two open-ended stories to choose from when they begin, allowing them to select one for their comic creation.",
   Rule4:"4. Time Allocation: A total of 2 hours and 15 minutes will be given to participants to finish their comic. A 15-minute period is set aside for the exclusive use of mobile phones for reference purposes.",
   Rule5:"5.All judging decisions are final and binding. No appeals or disputes will be entertained. The event coordinators reserve the right to disqualify any participant at any time during the event.",
   Rule6:null,
   EventHead1:"Varshini Karthikeyan",
   Contact1:"9499927043",
   EventHead2:" Nevethitha B",
   Contact2:"9789744889",
   link:"https://forms.gle/YFU5WNXY3CCdCUdj7",
   Timing: "12:30-3:00 PM",
    Venue: "KS02 (Idea Factory) - Rajalakshmi Engineering College"

},
{   id:"4",
    EventName:"CLONE QUEST",
    Participants:"Solo/Team [Max:3]",
    EventDescription_p1:"Unleash your creativity and technical skills in our exciting web design showcase! Participants will create replicas of a designated website using HTML, CSS, and JavaScript. This event is set to engage and motivate web enthusiasts of all levels. Get ready for an exciting showcase of innovation and technical expertise, with two levels of competition designed to accommodate different participant numbers.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:"Level 1",
   Round1:"Participants are given the challenge of designing a basic web page layout using JS, HTML, and CSS.",
   Round2Title:"Level 2",
   Round2:"Participants are tasked with cloning a website that features dynamic animations and content retrieved from an external API.",

   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either as an individual or a team of 3.",
   Rule2:"2. Participants should come equipped with their own laptops and have the necessary software installed for web development, such as code editors and browsers. Additionally, participants will be expected to deploy the website and upload their code to GitHub.",
   Rule3:"3. There will be a designated time limit for cloning the website, which is set at 2-3 hours. Participants are required to strictly follow the designated time limit. ",
   Rule4:"4. All judging decisions are final and binding. No appeals or disputes will be entertained. The event coordinators reserve the right to disqualify any participant at any time during the event.",
   Rule5:"5. Participants who cannot bring their laptops need to inform the event coordinator 1 day before the event and the reach the venue early to install necessary software in the allocated device.",
   Rule6:null,
   EventHead1:" Saroshmi B",
   Contact1:"9363333197",
   EventHead2:"Sathish",
   Contact2:"9384344297",
   link:"https://forms.gle/BeYSTsqgngttU53LA",
   Timing: "12:00 - 3:00 PM",
Venue: "JR1 (Library Block) - Rajalakshmi Engineering College"


},
{   id:"5",
    EventName:"Cut Short",
    Participants:"Solo/Team [Max:2]",
    EventDescription_p1:"In this challenge, contestants are given the task of reducing a feature-length film to its essential elements and showcasing their technical expertise and creative abilities through a concise and engaging video presentation.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2Title:null,
   Round2:null,

   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. The participants will be given one hour to edit the film that they will receive in video format. The participants will have the opportunity to import or download audio files from the internet just before the timer begins.",
   Rule2:"2. Premiere Pro's built-in tools are all that's needed for editing. There is a strict no-plugins-or-asset-packs policy.",
   Rule3:"3. Participants will be judged based on the quality of their edits and their ability to capture the essence of the movie, their interpretation and proper use of SFX wherever needed.",
   Rule4:"4. All judging decisions are final and binding. No appeals or disputes will be entertained. The event Coordinator reserves the right to disqualify any participant at any time during the event.",
   Rule5:null,
   Rule6:null,
   EventHead1:"Haroon Rasheed",
   Contact1:"8122182469",
   EventHead2:"Deepak",
   Contact2:"9710738126",
   link:"https://forms.gle/Vib8Uavsn7McNNr59",
   Timing: "12:00 - 3:00 PM",
Venue: "Jl1 (Library Block) - Rajalakshmi Engineering College"

},

];
// ------------------------------------------------------------------------------------------------------------------------------------------------

export const EventName=[
{ id: 1, name: "Code Crunch" },
  { id: 2, name: "Beyond Buttons(UI/UX)" },
  { id: 3, name: "Trademark" },
  { id: 4, name: "Clone Quest" },
  { id: 5, name: "Cut Short" },
  { id: 8, name: "Story Arcs" },
  { id: 6, name: "Movie Minds" },
  { id: 7, name: "Best Out of waste" },
  ];



  export const WorkshopDetails=[{
    id:"1",
    name:"Video Editing",
    registration:"150 members",
    D1:"Participate in an engaging and practical class specifically tailored to enhance your proficiency in video editing. Whether you are a beginner hoping to acquire fundamental knowledge or an advanced editor aiming to enhance your abilities, this session is specifically designed to cater to your requirements.",
    D2:"This hands-on video editing workshop will teach participants the essential skills needed to create professional-quality videos using Adobe Premiere Pro. Through a combination of demonstrations and hands-on practice, attendees will learn how to navigate the Premiere Pro interface, import and organize media, assemble footage into a coherent narrative, apply basic editing techniques, insert transitions and titles, and export their final projects. The workshop will cover the fundamental principles of video editing, including pacing, shot composition, and storytelling. By the end of the session, participants will have the confidence and competence to begin editing their own video projects.",
    R1:"Entry is on a first come and first serve basis.",
    R2:"Labs with the required facilities will be provided.Participants can feel free to bring their own laptops with chargers if they wish to do so.",
    R3:"Participants are requested to bring their own laptops with Adobe Premiere Pro installed to avoid any inconveniences.",
    R4:"After the workshop has concluded a time period of 30 minutes has been set aside for possible doubts and clarifications.",
    Timing:"9 AM -11:30 AM",
    Venue:"KS01 (Idea Factory Block) - Rajalakshmi Engineering College",
    Head1:"Ashwin Sha",
    Contact1:" 8122182469",
    Head2:"Swayam Prakash",
    Contact2:"8838023321",
    Link:"https://forms.gle/wxGHqDxArHQZe3my6"

  },{
    id:"2",
    name:"UI/UX",
    registration:"135 members",
    D1:"This comprehensive UI/UX workshop will provide participants with a solid foundation in the principles and best practices of user interface (UI) and user experience (UX) design. The first half of the workshop will solely be dedicated to teaching the fundamentals, tips and tricks of Adobe Photoshop.Through a mix of theory and hands-on exercises, attendees will learn the value of UI/UX in the industry, including how it drives customer engagement and business success. The workshop will cover UI/UX fundamentals, design thinking, wireframing, prototyping, and testing. By the end of the session, attendees will have the knowledge and skills to create intuitive, user-centric digital experiences.",
    D2:null,
    R1:"Entry is on a first come and first serve basis.",
    // R2:"Labs with the required facilities will be provided.Participants can feel free to bring their own laptops with chargers if they wish to do so.",
    R2:"After the workshop has concluded a time period of 30 minutes has been set aside for possible doubts and clarifications",
    Timing:"8:30 AM -2:30 PM",
    Venue:"KS03 (Idea Factory Block) - Rajalakshmi Engineering College",
    Head1:"Sudheer",
    Contact1:"6305950525",
    Head2:"Shyam Prasath",
    Contact2:"8220953013",
    Link:"https://forms.gle/YZXbdKYs5XzWdZiH8"
  }];