export const EventData=[{
    id:"1",
   EventName:"Code Crunch",
   Participants:"Solo",
   EventDescription_p1:"Participants solve a variety of coding difficulties and puzzles on their own during the solo coding challenge. With a focus on efficiency, they strive to tackle numerous challenges, showcasing their ability to solve problems and their strong coding skills, all while working against the clock.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound:null,
   Round1Title:"Round 1",
   Round1:" The first round will be conducted online, assessing participants' understanding of basic coding concepts.",
   Round2Title:null,
   Round2:null,
   Extraline1:"Estimated time: one and a half hours. ",
   Extraline2:"Only candidates who meet the criteria will advance to Round 2.",
   Extraline3:"In the second round, participants will be tested offline to assess their ability to understand problem statements. Duration: 1 hour.",
   Rule1:"1. Eligibility: The event is open to individuals with coding proficiency, irrespective of experience level.",
   Rule2:"2. Registration: Participants must register online through the event's official website or designated platform. Join the Brain Hack event within the specified time frame.",
   Rule3:"3. Test Cases: Code submissions will be evaluated based on their ability to pass predefined test cases. The number of test cases passed will contribute to the overall score.",
   Rule4:"4. Judging Decisions: All judging decisions are final and binding. No appeals or disputes will be entertained.",
   Rule5:"5. Platform Usage: Participants must exclusively use HackerRank platform for all coding tasks. Switching tabs or copy-pasting from external sources during the contest is strictly prohibited and will be considered malpractice.",
   Rule6:"6. Code Submission: All code submissions must be made within the specified time frame on HackerRank platform. Late submissions will not be accepted.",
   EventHead:"MANO DHASHIN D.",
   Contact:"9025067200",
   link:"https://forms.gle/BMf6G9auSNX2HVqJ6"
},{
    id:"2",
    EventName:"Beyond Buttons(UI/UX)",
    Participants:"Solo/Team",
    EventDescription_p1:"A UI/UX-based event known as Beyond presents participants with a problem statement that necessitates unique and inventive solutions. The objective of a UI/UX event is to empower and inspire individuals to develop digital experiences that prioritize users. And create innovative designs to enhance the user interface style for the provided problem statement.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:"Preliminary Round",
   PreliminaryRound:"During this stage, participants will be tasked with creating a UI for an app or website using Figma online. They will need to refer to a given problem statement for guidance. Candidates will be evaluated solely on their Figma submissions, as images will not be considered as design work.",
   Round1Title:"UX Round",
   Round1:"Participants will be given a problem statement and will need to come up with a suitable solution. They will then need to document both the problem and its solution to present to the judging panel. They need to promptly convert this concept into a wireframe, which illustrates the structure and layout of the digital interface.",
   Round2Title:"UI Design Build",
   Round2:"Participants will enhance their wireframes to create visually captivating UI designs. They will prioritize the integration of color schemes, typography, imagery, and interactive elements according to their wireframes. Paying close attention to detail, being creative, and following design principles are crucial for this round",
   Extraline1:"Finally, the participants who made it through rounds 1 and 2 will need to showcase their design work to the judges for the final evaluation.",
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either individuals or a team of 2-3 members.",
   Rule2:"2. In the preliminary round, participants must use Figma exclusively for design work, and they are required to share their designs as Figma file links. Images will not be accepted for evaluation.    Participants are allowed to use Figma, Adobe XD and Photoshop Only at the further rounds after the prelims.",
   Rule3:"3. Participants are permitted to utilize Figma, Adobe XD, and Photoshop only in the subsequent rounds following the preliminary stage.",
   Rule4:"4. Participants have to present their design work for the final evaluation.",
   Rule5:"5. Participants are advised to bring their laptops with full charge and are advised to carry their charger.",
   Rule6:"6. Code Submission: All code submissions must be made within the specified time frame on HackerRank platform. Late submissions will not be accepted.",
   EventHead:"Lingesh",
   Contact:"97908 95966",
   link:"https://forms.gle/1qTu6FjMB2VWmRSG7"
},{
    id:"3",
    EventName:"Best Out of waste",
    Participants:"Team",
    EventDescription_p1:"Best Out of Waste is an event where participants have the opportunity to showcase their creativity by repurposing old or unused items into innovative and practical creations. These items could range from bottles and clothes to plastic items and more. The primary focus is to transform these items into something creative and practical.",
   EventDescription_p2:"Material Selection: Participants have the freedom to choose from a variety of old or unused items, including bottles, clothes, plastic items, and more.",
   EventDescription_p3:" Emphasizing creativity: Participants are urged to explore innovative approaches and generate distinctive concepts for the transformation of these items. Creativity is essential, whether it's expressed through painting, cutting, sewing, or any other method.",
   EventDescription_p4:" Functionality: In addition to being creative, participants should also take into account the practicality of their creations. The transformed items should have a practical purpose, whether it's for decoration, functionality, or a combination of both.",
   EventDescription_p5:"Presentation: Participants will have the chance to showcase their creations to the judges and other attendees. They should be ready to discuss their creative process and the inspiration behind their designs.",
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either individuals or a team of 2-3 members.",
   Rule2:"2.The items required for the event, including old or unused items for transformation, should be procured by the participants themselves.",
   Rule3:"3. Organizers will not provide any additional materials or equipment during the event.",
   Rule4:"4. It is the participant's responsibility to double-check their supplies before the event to avoid any inconvenience or disruptions during the creation process.",
   Rule5:"5.   Participants are requested to avoid plastic items.",
   Rule6:null,
   EventHead:"NAREN MB",
   Contact:"9025770851",
   link:"https://forms.gle/6ve9vZFZStZ5r9mp9"
   
},{
    id:"4",
    EventName:"Movie Minds",
    Participants:"Solo/Team",
    EventDescription_p1:"An interactive occasion, a movie quiz challenges attendees to demonstrate their expertise in the realm of cinema by posing trivia inquiries. It's an exciting adventure that challenges your memory, sharp eye for detail, and passion for film. Infusing the quiz with a captivating and spirited twist. The goal is to engage and push the participants by assessing their understanding of movies. Our goal is to captivate participants by providing an enjoyable and interactive experience through trivia.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Open to all participants either individuals or a team of 2-3 members.",
   Rule2:"2. Participants should refrain from using mouth motions",
   Rule3:"3. Participants shouldn't ask for assistance from others.",
   Rule4:"4. After receiving one warning, the team will be eliminated twice.",
   Rule5:null,
   Rule6:null,
   EventHead:"Madhumita M",
   Contact:"90802 24846",
   link:"https://forms.gle/qxpYV2s5QTxvGPGV8"
},
{  
    id:"5",
    EventName:"TRADEMARK",
    Participants:"Solo/Team",
    EventDescription_p1:"Join our exciting Logo Design Competition! And demonstrate your design skills by creating a one-of-a-kind logo that perfectly captures the essence of the given theme. We are looking for unique and visually captivating logos that perfectly represent our chosen theme. This competition offers participants the opportunity to showcase their exceptional design skills and potentially influence the brand identity of a significant organization or cause.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Usage of mobile phones during the competition is strictly prohibited.",
   Rule2:"2. Participants are allowed to use Google only during the ideation phase (15 mins)",
   Rule3:"3. Participants are allowed to use only Adobe Photoshop, Illustrator and Figma to design logos.",
   Rule4:"4. Participants are advised to bring their laptops fully charged.",
   Rule5:null,
   Rule6:null,
   EventHead:"Bharathi K",
   Contact:"9940647260",
   link:"https://forms.gle/VVj1qGLtuX96fQqt7"
},
{   id:"6",
    EventName:"STORY ARCS",
    Participants:"Solo",
    EventDescription_p1:"Story Arcs is a comic competition where participants have the opportunity to showcase their creativity by adapting open-ended stories into comics, developing wordless narratives, and sketching stories. This event provides a platform for artists to express their creativity and captivate audiences through immersive visual storytelling. Artists demonstrate their storytelling abilities through illustrations.",
   EventDescription_p2:"Participants are given Comic frames (A3 sheet) and themes to work on!",
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2:null,
   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Format and Supplies: Participants will receive A3 sheets with comic grids.Every participant must remember to bring their own art supplies.",
   Rule2:"2. Theme Selection: Participants will be presented with two open-ended stories to choose from when they begin, allowing them to select one for their comic creation.",
   Rule3:"3. Time Allocation: A total of 2 hours and 15 minutes will be given to participants to finish their comic.A 15-minute period is set aside for the exclusive use of mobile phones for reference purposes",
   Rule4:null,
   Rule5:null,
   Rule6:null,
   EventHead:"Varshini Karthikeyan",
   Contact:"9499927043",
   link:"https://forms.gle/YFU5WNXY3CCdCUdj7"
},
{   id:"7",
    EventName:"CLONE QUEST",
    Participants:"Solo/Team",
    EventDescription_p1:"Unleash your creativity and technical skills in our exciting web design showcase! Participants will create replicas of a designated website using HTML, CSS, and JavaScript. This event is set to engage and motivate web enthusiasts of all levels. Get ready for an exciting showcase of innovation and technical expertise, with two levels of competition designed to accommodate different participant numbers.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:"Level 1",
   Round1:"Level 1: Participants are given the challenge of designing a basic web page layout using JS, HTML, and CSS.",
   Round2Title:"Level 2",
   Round2:"Participants are tasked with cloning a website that features dynamic animations and content retrieved from an external API.",

   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. Eligibility: The event welcomes participants, whether they are individuals or teams of up to 3 members.",
   Rule2:"2. Preparation: Participants should come equipped with their own laptops and have the necessary software installed for web development, such as code editors and browsers. Additionally, participants will be expected to deploy the website and upload their code to GitHub.",
   Rule3:"3. There will be a designated time limit for cloning the website, which is set at 2-3 hours. Participants are required to strictly follow the designated time limit.",
   Rule4:null,
   Rule5:null,
   Rule6:null,
   EventHead:" Saroshmi B",
   Contact:"9363333197",
   link:"https://forms.gle/BeYSTsqgngttU53LA"
},
{   id:"8",
    EventName:"Cut Short",
    Participants:"Solo/Team",
    EventDescription_p1:"The objective of the competitive video editing event CutShot is to demonstrate the participant's competence by modifying a pre-selected film to a specific score. Each contestant must be well-versed in the assigned content and have a firm grasp of the basics of video editing. In this challenge, contestants are given the task of reducing a feature-length film to its essential elements and showcasing their technical expertise and creative abilities through a concise and engaging video presentation.",
   EventDescription_p2:null,
   EventDescription_p3:null,
   EventDescription_p4:null,
   EventDescription_p5:null,
   PreliminaryRoundTItle:null,
   PreliminaryRound: null,
   Round1Title:null,
   Round1:null,
   Round2Title:null,
   Round2:null,

   Extraline1:null,
   Extraline2:null,
   Extraline3:null,
   Rule1:"1. The participants will be given one hour to edit the film that they will receive in video format. The participants will have the opportunity to import or download audio files from the internet just before the timer begins to run.",
   Rule2:"2. Premiere Pro's built-in tools are all that's needed for editing. There is a strict no-plugins-or-asset-packs policy. ",
   Rule3:null,
   Rule4:null,
   Rule5:null,
   Rule6:null,
   EventHead:"Haroon Rasheed",
   Contact:"98122182469",
   link:"https://forms.gle/Vib8Uavsn7McNNr59"
},

];
// ------------------------------------------------------------------------------------------------------------------------------------------------

export const EventName=[
{ id: 1, name: "Code Crunch" },
  { id: 2, name: "Beyond Buttons(UI/UX)" },
  { id: 3, name: "Best Out of waste" },
  { id: 4, name: "Movie Minds" },
  { id: 5, name: "TRADEMARK" },
  { id: 6, name: "STORY ARCS" },
  { id: 7, name: "CLONE QUEST" },
  { id: 8, name: "Cut Short" }];



  export const WorkshopDetails=[{
    id:"1",
    name:"Video Editing",
    registration:"150 members",
    D1:"Participate in an engaging and practical class specifically tailored to enhance your proficiency in video editing. Whether you are a beginner hoping to acquire fundamental knowledge or an advanced editor aiming to enhance your abilities, this session is specifically designed to cater to your requirements.",
    D2:"This 3-hour video editing workshop will teach participants the essential skills needed to create professional-quality videos using Adobe Premiere Pro. Through a combination of demonstrations and hands-on practice, attendees will learn how to navigate the Premiere Pro interface, import and organize media, assemble footage into a coherent narrative, apply basic editing techniques, insert transitions and titles, and export their final projects. The workshop will cover the fundamental principles of video editing, including pacing, shot composition, and storytelling. By the end of the session, participants will have the confidence and competence to begin editing their own video projects. The workshop will run from 9 am to 12 pm.",
    R1:"Entry is on a first come and first serve basis.",
    R2:"Labs with the required facilities will be provided.Participants can feel free to bring their own laptops with chargers if they wish to do so.",
    R3:"Participants are requested to bring their own laptops with Adobe Premiere Pro installed to avoid any inconveniences.All judging decisions are final and binding. No appeals or disputes will be entertained. The workshop Coordinator reserves the right to disqualify any participant at any time during the workshop.After the workshop has concluded a time period of 30 minutes has been set aside for possible doubts and clarifications.",
    Timing:"9am-11:30",
    Venue:"Rajalakshmi Engineering College",
    Head:"Ashwin Sha",
    Contact:" 81221 82469",
  },{
    id:"2",
    name:"UI/UX",
    registration:"135 members",
    D1:"This comprehensive UI/UX workshop will provide participants with a solid foundation in the principles and best practices of user interface (UI) and user experience (UX) design. Through a mix of theory and hands-on exercises, attendees will learn the value of UI/UX in the industry, including how it drives customer engagement and business success. The workshop will cover UI/UX fundamentals, design thinking, wireframing, prototyping, and testing. Additionally, participants will explore the practical applications of Adobe Photoshop software. By the end of the session, attendees will have the knowledge and skills to create intuitive, user-centric digital experiences. The workshop will run from 8 am to 2 pm.",
    D2:null,
    R1:"Entry is on a first come and first serve basis.",
    R2:"Labs with the required facilities will be provided.Participants can feel free to bring their own laptops with chargers if they wish to do so.",
    R3:"All judging decisions are final and binding. No appeals or disputes will be entertained. The workshop Coordinator reserves the right to disqualify any participant at any time during the workshop.After the workshop has concluded a time period of 30 minutes has been set aside for possible doubts and clarifications",
    Timing:"9am-2:30",
    Venue:"Rajalakshmi Engineering College",
    Head:"Sudheer",
    Contact:"6305950525",
  }];